### ISSUE TITLE
Does not resolve declared "through/m2m" tables

### ISSUE THREAD

**Issue by ranchodeluxe** [resulyrt93/pytest-sqlalchemy-mock#6] opened 2023-02-10 15:34 UTC
Great tool ✨ 

I'm able to get "most" model relationships mocked with this package. I'm running into trouble when mocking "secondary" (through/m2m) relationships in the following schema below. No errors occur on test setup which makes me think the insert into the sqllite is fine (maybe). The problem is that the relationship cannot be resolved and is empty when probed in the example tests below. But other simpler reverse fkey relationships resolve fine. 

Any sharp ideas on your end if I'm doing anything wrong here?

### model refs
`orm.Build.package_builds` has a secondary relationship:
https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/orm.py#L131

to this manually created m2m/through table:
https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/orm.py#L103-L112

### conftest.py

```python
import os
import sys
sys.path.append(os.path.join(os.getcwd(), 'conda-store-server'))

import pytest
from conda_store_server import orm, schema


@pytest.fixture(scope="function")
def sqlalchemy_declarative_base():
    return orm.Base


@pytest.fixture(scope="function")
def sqlalchemy_mock_config():
    return [("build", [
        {
            "id": 1,
            "specification_id": 1,
            "environment_id": 1,
            "status": schema.BuildStatus.COMPLETED,
        },
    ]),("build_artifact", [
        {
            "id": 1,
            "build_id": 1,
            "artifact_type": schema.BuildArtifactType.LOCKFILE
        }
    ]),("build_conda_package_build", [
        {
            "build_id": 1,
            "conda_package_build_id": 1,
        },
        {
            "build_id": 1,
            "conda_package_build_id": 2,
        },
    ]),("conda_package_build", [
        {
            "id": 1,
            "package_id": 1,
            "channel_id": 1,
            "subdir": "linux-64",
            "build": "h27087fc_0",
            "build_number": 1,
            "depends": "[]",
            "sha256": "sha256",
            "size": 2314454,
            "tarball_ext": ".conda",
            "md5": "87473a15119779e021c314249d4b4aed",
        },
        {
            "id": 2,
            "package_id": 2,
            "channel_id": 1,
            "subdir": "linux-64",
            "build": "pyhd8ed1ab_0",
            "build_number": 1,
            "depends": "[]",
            "sha256": "sha256",
            "size": 2314454,
            "tarball_ext": ".tar.bz2",
            "md5": "37d4251d34eb991ff9e40e546cc2e803",
        },
    ]),("conda_package", [
        {
            "id": 1,
            "channel_id": 1,
            "name": "icu",
            "version": "70.1",
        },
        {
            "id": 2,
            "channel_id": 1,
            "name": "zarr",
            "version": "2.12.0",
        }
    ]),("conda_channel", [
        {
            "id": 1,
            "name": "https://conda.anaconda.org/conda-forge"
        },
    ])
    ]


```

### test_model.py

```python
from conda_store_server import orm, schema, api
import sys


def test_mocked_toolchain_example(mocked_session):
    # an example making sure the mocking toolchain works
    build = mocked_session.query(orm.Build).filter_by(id=1).first()
    assert build.status == schema.BuildStatus.COMPLETED

    build_artifact = mocked_session.query(orm.BuildArtifact).filter_by(id=1).first()
    assert build_artifact.artifact_type == schema.BuildArtifactType.LOCKFILE

    # THIS IS SUSPICIOUSLY EMPTY ALWAYS
    print(f"[ CPB ]: {build.package_builds}")

    # BUT OTHER M2O RELATIONSHIPS RESOLVE FINE
   print(f"[ ARTIFACTS ]: {build.build_artifacts})
```

**Comment by ranchodeluxe** [comment] 2023-02-10 19:23
okay, the issue is that m2m table isn't necessarily inheriting from `Base`

**Comment by resulyrt93** [comment] 2023-03-15 16:59
I can't reproduce your case in my local, it throws error about conda. :/ Could you please try with our latest release `0.1.5`? We solved assocation table problem with that release. I guess that it should be fixed. [here](https://github.com/resulyrt93/pytest-sqlalchemy-mock/releases/tag/v0.1.5) is the release.

**Closed as completed** 2023-06-11 14:52 UTC
Labels: good first issue
